const API_URL='https://script.google.com/macros/s/AKfycbxcLP0TjVzWA3rBxqhIKvqYjd3PUfPcVrfq_5qrn4GF8-R90lsJmS7wF1nQ0nQWMVe8/exec';
let currentUser=null,currentCourse=null,examAnswers={};
async function api(action,payload={}){const r=await fetch(API_URL,{method:'POST',body:JSON.stringify({action,...payload})});const d=await r.json();if(!d.success)throw new Error(d.message||'حدث خطأ');return d}
function E(s){return String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
async function login(){try{const employeeID=document.getElementById('employeeID').value.trim(),pin=document.getElementById('pin').value.trim();const d=await api('login',{employeeID,pin});currentUser=d.user;localStorage.setItem('bahraUser',JSON.stringify(currentUser));showApp();await refresh()}catch(e){alert(e.message)}}
function showApp(){document.getElementById('loginPage').classList.add('hidden');document.getElementById('app').classList.remove('hidden');document.getElementById('userName').textContent=currentUser.name;document.getElementById('userRole').textContent=currentUser.role;document.querySelectorAll('[data-role]').forEach(x=>x.classList.toggle('hidden',!x.dataset.role.split(',').includes(currentUser.role)))}
async function refresh(){await loadDashboard();await loadCourses();await loadMyCourses();await loadMyRequests();await loadNotifications()}
async function loadDashboard(){const d=await api('dashboard',{employeeID:currentUser.employeeID});['Employees','Courses','Pending','Certificates'].forEach(k=>document.getElementById('kpi'+k).textContent=d[k==='Employees'?'employees':k==='Courses'?'courses':k==='Pending'?'pendingRequests':'certificates'])}
async function loadCourses(){const d=await api('courses');document.getElementById('courseList').innerHTML=d.courses.map(c=>`<article class="card"><span>${E(c.category)}</span><h3>${E(c.name)}</h3><p>${E(c.objective)}</p><button onclick="requestCourse('${E(c.id)}')">طلب الدورة</button></article>`).join('')}
async function requestCourse(id){try{const d=await api('trainingRequest',{employeeID:currentUser.employeeID,courseID:id});alert(d.message);await loadMyRequests()}catch(e){alert(e.message)}}
async function loadMyRequests(){const d=await api('myRequests',{employeeID:currentUser.employeeID});document.getElementById('requestList').innerHTML=d.requests.map(r=>`<div class="row"><b>${E(r.course)}</b><span>${E(r.status)}</span></div>`).join('')||'لا توجد طلبات'}
async function loadMyCourses(){const d=await api('myCourses',{employeeID:currentUser.employeeID});document.getElementById('myCourseList').innerHTML=d.courses.map(c=>`<article class="card"><h3>${E(c.course)}</h3><p>${c.progress}%</p><button onclick="openCourse('${E(c.courseID)}')">فتح الدورة</button></article>`).join('')||'لا توجد دورات'}
async function openCourse(id){try{const d=await api('courseDetails',{courseID:id});currentCourse=d.course;document.getElementById('playerTitle').textContent=currentCourse.name;document.getElementById('moduleList').innerHTML=currentCourse.modules.map(m=>`<div class="row"><div><b>${E(m.title)}</b><p>${E(m.description)}</p></div><button onclick="completeModule('${E(m.id)}')">إكمال</button></div>`).join('');document.getElementById('coursePlayer').classList.remove('hidden')}catch(e){alert(e.message)}}
async function completeModule(mid){try{const d=await api('completeModule',{employeeID:currentUser.employeeID,courseID:currentCourse.id,moduleID:mid});document.getElementById('playerProgress').textContent=d.progress+'%';await loadMyCourses()}catch(e){alert(e.message)}}
async function startExam(){try{const d=await api('exam',{employeeID:currentUser.employeeID,courseID:currentCourse.id});examAnswers={};document.getElementById('examQuestions').innerHTML=d.questions.map((q,i)=>`<div class="question"><h4>${i+1}. ${E(q.question)}</h4>${q.options.map(o=>`<label><input type="radio" name="q_${E(q.id)}" onchange="examAnswers['${E(q.id)}']='${E(o.key)}'"> ${E(o.text)}</label>`).join('')}</div>`).join('');document.getElementById('examBox').classList.remove('hidden')}catch(e){alert(e.message)}}
async function submitExam(){try{const d=await api('submitExam',{employeeID:currentUser.employeeID,courseID:currentCourse.id,answers:examAnswers});document.getElementById('examResult').innerHTML=`<h3>${d.result==='Pass'?'ناجح':'غير ناجح'} - ${d.score}%</h3>${d.certificateID?'<p>'+E(d.certificateID)+'</p>':''}`;await loadMyCourses()}catch(e){alert(e.message)}}
async function loadManagerRequests(){try{const d=await api('managerRequests',{employeeID:currentUser.employeeID});document.getElementById('managerRequests').innerHTML=d.requests.map(r=>`<div class="row"><div><b>${E(r.employee)}</b><p>${E(r.course)}</p></div><div><button onclick="managerDecision('${E(r.id)}','Approved')">موافقة</button> <button onclick="managerDecision('${E(r.id)}','Rejected')">رفض</button></div></div>`).join('')||'لا توجد طلبات'}catch(e){alert(e.message)}}
async function managerDecision(id,decision){const d=await api('managerDecision',{employeeID:currentUser.employeeID,requestID:id,decision});alert(d.message);loadManagerRequests()}
async function loadHRRequests(){try{const d=await api('hrRequests',{employeeID:currentUser.employeeID});document.getElementById('hrRequests').innerHTML=d.requests.map(r=>`<div class="row"><div><b>${E(r.employee)}</b><p>${E(r.department)} - ${E(r.course)}</p></div><div><button onclick="hrDecision('${E(r.id)}','Approved')">اعتماد</button> <button onclick="hrDecision('${E(r.id)}','Rejected')">رفض</button></div></div>`).join('')||'لا توجد طلبات'}catch(e){alert(e.message)}}
async function hrDecision(id,decision){const d=await api('hrDecision',{employeeID:currentUser.employeeID,requestID:id,decision});alert(d.message);loadHRRequests()}
async function loadCertificates(){const d=await api('certificates',{employeeID:currentUser.employeeID});document.getElementById('certificateList').innerHTML=d.certificates.map(c=>`<div class="row"><b>${E(c.course)}</b><span>${E(c.id)} - ${c.score}%</span></div>`).join('')||'لا توجد شهادات'}
async function loadNotifications(){const d=await api('notifications',{employeeID:currentUser.employeeID});document.getElementById('notificationList').innerHTML=d.notifications.map(n=>`<div class="row"><b>${E(n.title)}</b><span>${E(n.message)}</span></div>`).join('')||'لا توجد إشعارات'}
function showTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');if(id==='managerTab')loadManagerRequests();if(id==='hrTab')loadHRRequests();if(id==='certificatesTab')loadCertificates()}
function logout(){localStorage.removeItem('bahraUser');location.reload()}
document.addEventListener('DOMContentLoaded',()=>{try{currentUser=JSON.parse(localStorage.getItem('bahraUser')||'null')}catch(e){}if(currentUser){showApp();refresh()}})
